### ISSUE TITLE
output example

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/Mykrobe_tb_workflow#3]
Looking very nice @mbhall88  - could you maybe add a screenshot of some standard output? or add some demo output in a demo directory, and link to it from the front page, somewhere high enough they dont need to scroll through it all to find it?

**Comment by mbhall88** [comment]
Example here https://rawgit.com/iqbal-lab-org/Mykrobe_tb_workflow/master/docs/example_report.html
